/*
 * 2011 Foxykeep (http://datadroid.foxykeep.com)
 *
 * Licensed under the Beerware License :
 * 
 *   As long as you retain this notice you can do whatever you want with this stuff. If we meet some day, and you think
 *   this stuff is worth it, you can buy me a beer in return
 */
package com.foxykeep.datadroid.config;

@SuppressWarnings("all")
public class LogConfig {

    private LogConfig() {
    }

    /**
     * Log Level variables
     */
    private static final int DP_LOG_LEVEL_DEBUG = 4;
    private static final int DP_LOG_LEVEL_INFO = 3;
    private static final int DP_LOG_LEVEL_WARNING = 2;
    private static final int DP_LOG_LEVEL_ERROR = 1;
    private static final int DP_LOG_LEVEL_NONE = 0;

    /**
     * Set this flag to {@link LogConfig#DP_LOG_LEVEL_NONE} when releasing your
     * application in order to remove all logs generated by DataDroid.
     */
    private static final int DP_LOG_LEVEL = DP_LOG_LEVEL_DEBUG;

    public static final boolean DP_DEBUG_LOGS_ENABLED = (DP_LOG_LEVEL == DP_LOG_LEVEL_DEBUG);
    public static final boolean DP_INFO_LOGS_ENABLED = DP_DEBUG_LOGS_ENABLED || (DP_LOG_LEVEL == DP_LOG_LEVEL_INFO);
    public static final boolean DP_WARNING_LOGS_ENABLED = DP_INFO_LOGS_ENABLED
            || (DP_LOG_LEVEL == DP_LOG_LEVEL_WARNING);
    public static final boolean DP_ERROR_LOGS_ENABLED = DP_WARNING_LOGS_ENABLED || (DP_LOG_LEVEL == DP_LOG_LEVEL_ERROR);
}
