/**
 * 2011 Foxykeep (http://datadroid.foxykeep.com)
 * <p>
 * Licensed under the Beerware License : <br />
 * As long as you retain this notice you can do whatever you want with this stuff. If we meet some
 * day, and you think this stuff is worth it, you can buy me a beer in return
 */

package com.foxykeep.datadroid.config;

import com.foxykeep.datadroid.BuildConfig;

@SuppressWarnings("all")
public final class LogConfig {

    private LogConfig() {
        // No public constructor
    }

    /**
     * Log Level variables.
     */
    private static final int DD_LOG_LEVEL_DEBUG = 4;
    private static final int DD_LOG_LEVEL_INFO = 3;
    private static final int DD_LOG_LEVEL_WARNING = 2;
    private static final int DD_LOG_LEVEL_ERROR = 1;
    private static final int DD_LOG_LEVEL_NONE = 0;

    /**
     * Set this flag to {@link LogConfig#DD_LOG_LEVEL_NONE} when releasing your application in order
     * to remove all logs generated by DataDroid.
     */
    private static final int DD_LOG_LEVEL = DD_LOG_LEVEL_DEBUG;

    public static final boolean DD_DEBUG_LOGS_ENABLED = (DD_LOG_LEVEL == DD_LOG_LEVEL_DEBUG)
            && BuildConfig.DEBUG;
    public static final boolean DD_INFO_LOGS_ENABLED = DD_DEBUG_LOGS_ENABLED
            || (DD_LOG_LEVEL == DD_LOG_LEVEL_INFO);
    public static final boolean DD_WARNING_LOGS_ENABLED = DD_INFO_LOGS_ENABLED
            || (DD_LOG_LEVEL == DD_LOG_LEVEL_WARNING);
    public static final boolean DD_ERROR_LOGS_ENABLED = DD_WARNING_LOGS_ENABLED
            || (DD_LOG_LEVEL == DD_LOG_LEVEL_ERROR);
}
