<?php 
header ("content-type: application/json");
echo "{
    persons:{
        person:[
            {
                firstName:'Valentine',
                lastName:'Wells',
                email:'arcu@loremegetmollis.edu',
                city:'Nacogdoches',
                postalCode:94082,
                age:15,
                isWorking:1
            },
            {
                firstName:'Ciaran',
                lastName:'Boyd',
                email:'dui@ut.com',
                city:'Lomita',
                postalCode:23818,
                age:18,
                isWorking:0
            },
            {
                firstName:'Kadeem',
                lastName:'Howe',
                email:'varius@Duismi.com',
                city:'Chino',
                postalCode:47742,
                age:20,
                isWorking:1
            },
            {
                firstName:'Ross',
                lastName:'Gates',
                email:'purus.sapien@nequeMorbi.ca',
                city:'Rapid City',
                postalCode:1501,
                age:5,
                isWorking:1
            },
            {
                firstName:'Maxine',
                lastName:'Johnston',
                email:'Duis.gravida@lectusrutrumurna.org',
                city:'Glendora',
                postalCode:95042,
                age:16,
                isWorking:0
            },
            {
                firstName:'Priscilla',
                lastName:'Watson',
                email:'pretium.et@elit.org',
                city:'Pittsburgh',
                postalCode:34846,
                age:15,
                isWorking:1
            },
            {
                firstName:'Lucian',
                lastName:'Roman',
                email:'ad@congue.com',
                city:'Corona',
                postalCode:2560,
                age:35,
                isWorking:0
            },
            {
                firstName:'Anthony',
                lastName:'Kelley',
                email:'ipsum@imperdieterat.com',
                city:'Poughkeepsie',
                postalCode:94438,
                age:45,
                isWorking:1
            },
            {
                firstName:'Erin',
                lastName:'Sanchez',
                email:'nunc.Quisque@vulputatevelit.edu',
                city:'Sun Valley',
                postalCode:60866,
                age:58,
                isWorking:1
            },
            {
                firstName:'Sierra',
                lastName:'Molina',
                email:'Quisque.ornare@diam.org',
                city:'Midland',
                postalCode:12517,
                age:29,
                isWorking:0
            },
            {
                firstName:'Amena',
                lastName:'Joseph',
                email:'Aliquam.rutrum@eget.com',
                city:'Tonawanda',
                postalCode:47408,
                age:63,
                isWorking:1
            },
            {
                firstName:'Erasmus',
                lastName:'Nelson',
                email:'vitae.purus@orci.edu',
                city:'Irving',
                postalCode:89892,
                age:28,
                isWorking:0
            },
            {
                firstName:'Germane',
                lastName:'Berger',
                email:'Proin.velit.Sed@neceleifend.org',
                city:'Sonoma',
                postalCode:3941,
                age:24,
                isWorking:0
            },
            {
                firstName:'Avye',
                lastName:'Kim',
                email:'placerat.velit@in.org',
                city:'Kokomo',
                postalCode:68948,
                age:18,
                isWorking:0
            },
            {
                firstName:'Oprah',
                lastName:'Griffin',
                email:'aliquam@nibhQuisque.com',
                city:'Winooski',
                postalCode:28225,
                age:64,
                isWorking:1
            }
        ]
    }
}";?>